config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "groups#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:index ,:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true


  def show_last_message
    if (last_message = messages.last).present?
      if last_message.messages?
        last_message.messages
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :messages, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_user
  has_many :groups ,through: :group_user
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id]
    if last_message_id == nil then
      last_message_id = 0
    end
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_messages_path(@group.id), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private
  def message_params
    params.require(:message).permit(:messages, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      .UserSearch
        %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #UserSearchResult
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, value: "チャットメンバー", class: "SettingGroupForm__label"
    .SettingGroupForm__rightField
      .ChatMembers
        .ChatMember
          %p.ChatMember__name= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        - group.users.each do |user|
          - if user.id != current_user.id
            .ChatMember
              %p.ChatMember__name= user.name
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              // <div class="ChatMember__remove ChatMember__button">削除</div>
              .ChatMember__remove.ChatMember__button= "削除"



  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.main
  .main__group-info
    .main__group-info--member
      .group-name
        = @group.name
      %ul.members
        %li Member:
        - @group.users.each do |user|
          %li.members__name 
            = user.name
    .main__group-info--edit
      = link_to edit_group_path(@group.id),class: "link__edit" do
        Edit
  .main__message-list
    = render partial: 'message', collection: @messages
  .main__message-form
    = form_with(model: [@group,@message], local: true, class: "form") do |f| 
      .form__message
        .form__message--text
          = f.text_field :messages, placeholder: "type a message" ,class: "input-form"
        .form__message--img
          = f.label :image ,icon("far","image")
          = f.file_field :image,style: "display: none"
      .form__btn
        = f.submit "SEND" ,class: "form__btn--send"

app/views/messages/_message.html.haml
.main__message-list--block{data: {message: {id: message.id}}}
  .header
    .header__name
      = message.user.name
    .header__date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .body
    = message.messages
    = image_tag message.image.url, class: 'Message__image' if message.image.present?

app/views/messages/_side_bar.html.haml
.side
  %header.side__username
    .top
      .top__name
        = current_user.name
      .top__icons
        = link_to new_group_path, class: "top__icons--icon" do
          = icon("far","edit",class: "top__icons--edit")
        = link_to edit_user_path(current_user.id), class:"top__icons--icon" do
          = icon("fas","cog",class: "top__icons--gear")
  .side__grouplist
    - current_user.groups.each do |group|
      .side__group
        = link_to group_messages_path(group.id),class:"side__group--link" do
          .side__group--group-name
            = group.name
          .side__group--new-message
            = group.show_last_message

app/views/messages/index.html.haml
= javascript_include_tag 'autoReload'
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'